"""Initial migration

Revision ID: e44ba8b90235
Revises: f74f0880b611
Create Date: 2024-12-07 15:08:11.681371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'e44ba8b90235'
down_revision = 'f74f0880b611'
branch_labels = None
depends_on = None



def upgrade():
    inspector = inspect(op.get_bind())
    if 'test' not in inspector.get_table_names():
        op.create_table(
            'test',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(120), nullable=False),
            sa.Column('questions', sa.Text(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('test_result')
    op.drop_table('user')
    op.drop_table('test')
    # ### end Alembic commands ###
